export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  KEBELE_ADMIN = 'KEBELE_ADMIN',
  KEBELE_FACILITATOR = 'KEBELE_FACILITATOR',
}

export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_KEBELE_REVIEW = 'UNDER_KEBELE_REVIEW',
  MORE_INFORMATION_REQUIRED = 'MORE_INFORMATION_REQUIRED',
  RETURNED_FOR_CORRECTION = 'RETURNED_FOR_CORRECTION',
  KEBELE_ACCEPTED = 'KEBELE_ACCEPTED',
  KEBELE_REJECTED = 'KEBELE_REJECTED',
  SUBMITTED_TO_WEREDA = 'SUBMITTED_TO_WEREDA',
  RETURNED_BY_SUPER_ADMIN = 'RETURNED_BY_SUPER_ADMIN',
  SUPER_ADMIN_APPROVED = 'SUPER_ADMIN_APPROVED',
  SUPER_ADMIN_REJECTED = 'SUPER_ADMIN_REJECTED',
  ACTIVE_BENEFICIARY = 'ACTIVE_BENEFICIARY',
  SUSPENDED = 'SUSPENDED',
  CLOSED = 'CLOSED',
}

export enum ComplaintStatus {
  SUBMITTED = 'SUBMITTED',
  RECEIVED = 'RECEIVED',
  ASSIGNED = 'ASSIGNED',
  UNDER_INVESTIGATION = 'UNDER_INVESTIGATION',
  ESCALATED = 'ESCALATED',
  ACTION_TAKEN = 'ACTION_TAKEN',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  REUPLOAD_REQUIRED = 'REUPLOAD_REQUIRED',
}

export enum SupportType {
  FOOD = 'FOOD',
  CASH = 'CASH',
  EDUCATIONAL = 'EDUCATIONAL',
  HEALTHCARE = 'HEALTHCARE',
  HOUSING = 'HOUSING',
  EMPLOYMENT = 'EMPLOYMENT',
  AGRICULTURAL = 'AGRICULTURAL',
  EMERGENCY = 'EMERGENCY',
  SOCIAL_PROTECTION = 'SOCIAL_PROTECTION',
  OTHER = 'OTHER',
}

export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}
