// Application workflow statuses (SRS §11.1)
export enum ApplicationStatus {
  DRAFT = 'DRAFT',
  SUBMITTED = 'SUBMITTED',
  UNDER_KEBELE_REVIEW = 'UNDER_KEBELE_REVIEW',
  MORE_INFORMATION_REQUIRED = 'MORE_INFORMATION_REQUIRED',
  RETURNED_FOR_CORRECTION = 'RETURNED_FOR_CORRECTION',
  KEBELE_ACCEPTED = 'KEBELE_ACCEPTED',
  KEBELE_REJECTED = 'KEBELE_REJECTED',
  SUBMITTED_TO_WEREDA = 'SUBMITTED_TO_WEREDA',
  RETURNED_BY_SUPER_ADMIN = 'RETURNED_BY_SUPER_ADMIN',
  SUPER_ADMIN_APPROVED = 'SUPER_ADMIN_APPROVED',
  SUPER_ADMIN_REJECTED = 'SUPER_ADMIN_REJECTED',
  ACTIVE_BENEFICIARY = 'ACTIVE_BENEFICIARY',
  SUSPENDED = 'SUSPENDED',
  CLOSED = 'CLOSED',
}

// Complaint lifecycle statuses (SRS §5.4)
export enum ComplaintStatus {
  SUBMITTED = 'SUBMITTED',
  RECEIVED = 'RECEIVED',
  ASSIGNED = 'ASSIGNED',
  UNDER_INVESTIGATION = 'UNDER_INVESTIGATION',
  ESCALATED = 'ESCALATED',
  ACTION_TAKEN = 'ACTION_TAKEN',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

// Document statuses (SRS §12)
export enum DocumentStatus {
  UPLOADED = 'UPLOADED',
  UNDER_REVIEW = 'UNDER_REVIEW',
  VERIFIED = 'VERIFIED',
  REJECTED = 'REJECTED',
  EXPIRED = 'EXPIRED',
  REUPLOAD_REQUIRED = 'REUPLOAD_REQUIRED',
}

// User roles (SRS §4)
export enum UserRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  KEBELE_ADMIN = 'KEBELE_ADMIN',
  KEBELE_FACILITATOR = 'KEBELE_FACILITATOR',
}

// Decision levels (SRS §32)
export enum DecisionLevel {
  KEBELE = 'KEBELE',
  WEREDA = 'WEREDA',
}

// Decision types
export enum DecisionType {
  ACCEPT = 'ACCEPT',
  REJECT = 'REJECT',
  RETURN = 'RETURN',
  MORE_INFO = 'MORE_INFO',
  ACCEPT_ALL = 'ACCEPT_ALL',
  REJECT_ALL = 'REJECT_ALL',
}

// Gender
export enum Gender {
  MALE = 'MALE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
}

// Support types (SRS §18)
export enum SupportType {
  FOOD = 'FOOD',
  CASH = 'CASH',
  EDUCATIONAL = 'EDUCATIONAL',
  HEALTHCARE = 'HEALTHCARE',
  HOUSING = 'HOUSING',
  EMPLOYMENT = 'EMPLOYMENT',
  AGRICULTURAL = 'AGRICULTURAL',
  EMERGENCY = 'EMERGENCY',
  SOCIAL_PROTECTION = 'SOCIAL_PROTECTION',
  OTHER = 'OTHER',
}

// Feedback status
export enum FeedbackStatus {
  SUBMITTED = 'SUBMITTED',
  REVIEWED = 'REVIEWED',
  ADDRESSED = 'ADDRESSED',
  CLOSED = 'CLOSED',
}
